FROM --platform=linux/amd64 node:19.3.0 AS base

# copy project resources
WORKDIR /home/node/app

COPY tsconfig.json ./
COPY next-env.d.ts ./
COPY next.config.js ./
COPY package.json ./
COPY yarn.lock ./
COPY src ./src
RUN yarn install --non-interactive --immutable

ARG NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
RUN echo > .env
RUN echo NEXT_PUBLIC_BASE_URL=\"${NEXT_PUBLIC_BASE_URL}\" >> .env

# run build
ENV NODE_ENV=production
RUN yarn build
CMD yarn start
