import { ResumeStylePreset } from './types';

export const resumePresets: Record<string, ResumeStylePreset> = {
  academic: {
    colors: {
      accent: '#8b0000',
      background: '#fefefe',
      headerBackground: '#2f4f4f',
      headerText: '#f5f5f5',
      primary: '#2f4f4f',
      secondary: '#696969',
      text: '#1a1a1a',
    },
    description: 'Traditional academic CV layout with publications focus',
    id: 'academic',
    layout: 'single-column',
    name: 'Academic',
    sections: {
      order: ['header', 'summary', 'education', 'experience', 'projects', 'skills'],
      visible: {
        education: true,
        projects: true,
        skills: true,
        summary: true,
      },
    },
    spacing: {
      itemGap: '1.2rem',
      padding: '1.5rem',
      sectionGap: '2rem',
    },
    styles: { header: { borderBottom: '2px double #2f4f4f', paddingBottom: '1rem' } },
    typography: {
      baseFontSize: 'clamp(8.5px, 0.85vw, 11.5px)',
      fontFamily: '"Crimson Text", "Book Antiqua", serif',
      headerFontSize: '2.2rem',
      lineHeight: 1.7,
    },
  },
  classic: {
    colors: {
      accent: '#4a90e2',
      background: 'white',
      headerBackground: '#1a1a1a',
      headerText: 'white',
      primary: '#1a1a1a',
      secondary: '#595959',
      text: '#1a1a1a',
    },
    description: 'Traditional two-column layout with clean typography',
    id: 'classic',
    layout: 'two-column',
    name: 'Classic',
    sections: {
      order: ['header', 'summary', 'experience', 'skills', 'education'],
      visible: {
        education: true,
        projects: true,
        skills: true,
        summary: true,
      },
    },
    spacing: {
      itemGap: '1rem',
      padding: '1rem',
      sectionGap: '1.5rem',
    },
    typography: {
      baseFontSize: 'clamp(8px, 0.8vw, 12px)',
      fontFamily: '"Helvetica Neue", Arial, sans-serif',
      headerFontSize: '2rem',
      lineHeight: 1.5,
    },
  },
  compact: {
    colors: {
      background: 'white',
      headerBackground: '#000000',
      headerText: 'white',
      primary: '#000000',
      secondary: '#595959',
      text: '#1a1a1a',
    },
    description: 'Dense single-column layout maximizing content per page',
    id: 'compact',
    layout: 'single-column',
    name: 'Compact',
    sections: {
      order: ['header', 'skills', 'experience', 'education'],
      visible: {
        education: true,
        projects: false,
        skills: true,
        summary: false,
      },
    },
    spacing: {
      itemGap: '0.5rem',
      padding: '0.75rem',
      sectionGap: '1rem',
    },
    typography: {
      baseFontSize: 'clamp(7px, 0.7vw, 10px)',
      fontFamily: 'Arial, sans-serif',
      headerFontSize: '1.5rem',
      lineHeight: 1.3,
    },
  },
  creative: {
    colors: {
      accent: '#c0392b',
      background: '#fafafa',
      headerBackground: 'linear-gradient(135deg, #4a5fd4 0%, #5a2d7a 100%)',
      headerText: 'white',
      primary: '#1a252f',
      secondary: '#5a6c7d',
      text: '#1a252f',
    },
    description: 'Bold design with accent colors and modern typography',
    id: 'creative',
    layout: 'sidebar',
    name: 'Creative',
    sections: {
      order: ['header', 'summary', 'experience', 'skills', 'education', 'projects'],
      visible: {
        education: true,
        projects: true,
        skills: true,
        summary: true,
      },
    },
    spacing: {
      itemGap: '1.2rem',
      padding: '1.5rem',
      sectionGap: '2rem',
    },
    styles: { section: { borderLeft: '3px solid #667eea', paddingLeft: '1rem' } },
    typography: {
      baseFontSize: 'clamp(8px, 0.85vw, 11px)',
      fontFamily: '"Segoe UI", Roboto, sans-serif',
      headerFontSize: '2.2rem',
      lineHeight: 1.6,
    },
  },
  elegant: {
    colors: {
      accent: '#d4af37',
      background: '#fffef9',
      headerBackground: 'linear-gradient(135deg, #2c3e50 0%, #3d5a80 100%)',
      headerText: '#f8f9fa',
      primary: '#2c3e50',
      secondary: '#6c757d',
      text: '#2c3e50',
    },
    description: 'Sophisticated serif typography with refined color palette',
    id: 'elegant',
    layout: 'two-column',
    name: 'Elegant',
    sections: {
      order: ['header', 'summary', 'experience', 'skills', 'education', 'projects'],
      visible: {
        education: true,
        projects: true,
        skills: true,
        summary: true,
      },
    },
    spacing: {
      itemGap: '1.2rem',
      padding: '1.5rem',
      sectionGap: '2rem',
    },
    styles: { header: { borderBottom: '1px solid #d4af37' } },
    typography: {
      baseFontSize: 'clamp(8px, 0.85vw, 11.5px)',
      fontFamily: '"Garamond", "Georgia", serif',
      headerFontSize: '2.3rem',
      lineHeight: 1.7,
    },
  },
  executive: {
    colors: {
      accent: '#b8860b',
      background: 'white',
      headerBackground: '#1a1a1a',
      headerText: '#ffffff',
      primary: '#1a1a1a',
      secondary: '#4a4a4a',
      text: '#1a1a1a',
    },
    description: 'Premium single-column layout for senior professionals',
    id: 'executive',
    layout: 'single-column',
    name: 'Executive',
    sections: {
      order: ['header', 'summary', 'experience', 'education', 'skills'],
      visible: {
        education: true,
        projects: false,
        skills: true,
        summary: true,
      },
    },
    spacing: {
      itemGap: '1.5rem',
      padding: '2rem',
      sectionGap: '2.5rem',
    },
    styles: { header: { borderBottom: '3px solid #b8860b', paddingBottom: '1.5rem' } },
    typography: {
      baseFontSize: 'clamp(9px, 0.9vw, 12px)',
      fontFamily: '"Baskerville", "Palatino", serif',
      headerFontSize: '2.8rem',
      lineHeight: 1.8,
    },
  },
  minimal: {
    colors: {
      background: 'white',
      headerBackground: 'white',
      headerText: '#000',
      primary: '#000',
      secondary: '#595959',
      text: '#000',
    },
    description: 'Clean, minimalist design with ample whitespace',
    id: 'minimal',
    layout: 'single-column',
    name: 'Minimal',
    sections: {
      order: ['header', 'experience', 'skills', 'education'],
      visible: {
        education: true,
        projects: true,
        skills: true,
        summary: false,
      },
    },
    spacing: {
      itemGap: '1.5rem',
      padding: '2rem',
      sectionGap: '2.5rem',
    },
    styles: { header: { borderBottom: '2px solid #000', paddingBottom: '1rem' } },
    typography: {
      baseFontSize: 'clamp(9px, 0.9vw, 12px)',
      fontFamily: '"Times New Roman", serif',
      headerFontSize: '2.5rem',
      lineHeight: 1.8,
    },
  },
  modern: {
    colors: {
      accent: '#0284c7',
      background: 'white',
      headerBackground: '#0f172a',
      headerText: 'white',
      primary: '#0f172a',
      secondary: '#475569',
      text: '#0f172a',
    },
    description: 'Contemporary sidebar layout with vibrant accents',
    id: 'modern',
    layout: 'sidebar',
    name: 'Modern',
    sections: {
      order: ['header', 'summary', 'experience', 'skills', 'education'],
      visible: {
        education: true,
        projects: true,
        skills: true,
        summary: true,
      },
    },
    spacing: {
      itemGap: '1rem',
      padding: '1.25rem',
      sectionGap: '1.75rem',
    },
    typography: {
      baseFontSize: 'clamp(8px, 0.82vw, 11.5px)',
      fontFamily: '"Inter", "system-ui", sans-serif',
      headerFontSize: '2rem',
      lineHeight: 1.6,
    },
  },
  professional: {
    colors: {
      accent: '#1d4ed8',
      background: 'white',
      headerBackground: '#1e3a8a',
      headerText: 'white',
      primary: '#1e3a8a',
      secondary: '#334155',
      text: '#0f172a',
    },
    description: 'Corporate-friendly layout with conservative styling',
    id: 'professional',
    layout: 'two-column',
    name: 'Professional',
    sections: {
      order: ['header', 'summary', 'experience', 'education', 'skills'],
      visible: {
        education: true,
        projects: true,
        skills: true,
        summary: true,
      },
    },
    spacing: {
      itemGap: '1rem',
      padding: '1rem',
      sectionGap: '1.5rem',
    },
    typography: {
      baseFontSize: 'clamp(8px, 0.8vw, 11px)',
      fontFamily: '"Calibri", "Helvetica", sans-serif',
      headerFontSize: '1.8rem',
      lineHeight: 1.5,
    },
  },
  startup: {
    colors: {
      accent: '#ff4757',
      background: 'white',
      headerBackground: '#2d3436',
      headerText: '#ffffff',
      primary: '#2d3436',
      secondary: '#636e72',
      text: '#2d3436',
    },
    description: 'Modern casual style perfect for startup environments',
    id: 'startup',
    layout: 'two-column',
    name: 'Startup',
    sections: {
      order: ['header', 'summary', 'experience', 'skills', 'projects', 'education'],
      visible: {
        education: true,
        projects: true,
        skills: true,
        summary: true,
      },
    },
    spacing: {
      itemGap: '1rem',
      padding: '1.25rem',
      sectionGap: '1.75rem',
    },
    styles: { section: { borderLeft: '3px solid #ff4757', paddingLeft: '0.75rem' } },
    typography: {
      baseFontSize: 'clamp(8px, 0.82vw, 11px)',
      fontFamily: '"Nunito", "Roboto", sans-serif',
      headerFontSize: '2.1rem',
      lineHeight: 1.6,
    },
  },
  tech: {
    colors: {
      accent: '#00ff88',
      background: '#0d1117',
      headerBackground: '#161b22',
      headerText: '#c9d1d9',
      primary: '#58a6ff',
      secondary: '#8b949e',
      text: '#c9d1d9',
    },
    description: 'Dark mode developer-focused theme with code aesthetics',
    id: 'tech',
    layout: 'sidebar',
    name: 'Tech',
    sections: {
      order: ['header', 'summary', 'experience', 'skills', 'projects', 'education'],
      visible: {
        education: true,
        projects: true,
        skills: true,
        summary: true,
      },
    },
    spacing: {
      itemGap: '1rem',
      padding: '1.25rem',
      sectionGap: '1.75rem',
    },
    styles: {
      container: { border: '1px solid #30363d' },
      section: { borderLeft: '2px solid #58a6ff', paddingLeft: '0.75rem' },
    },
    typography: {
      baseFontSize: 'clamp(8px, 0.8vw, 11px)',
      fontFamily: '"JetBrains Mono", "Fira Code", monospace',
      headerFontSize: '2rem',
      lineHeight: 1.6,
    },
  },
  vibrant: {
    colors: {
      accent: '#ff6b6b',
      background: 'white',
      headerBackground: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      headerText: 'white',
      primary: '#4c51bf',
      secondary: '#718096',
      text: '#2d3748',
    },
    description: 'Eye-catching gradient design with colorful accents',
    id: 'vibrant',
    layout: 'sidebar',
    name: 'Vibrant',
    sections: {
      order: ['header', 'summary', 'experience', 'skills', 'education', 'projects'],
      visible: {
        education: true,
        projects: true,
        skills: true,
        summary: true,
      },
    },
    spacing: {
      itemGap: '1.2rem',
      padding: '1.5rem',
      sectionGap: '2rem',
    },
    styles: { section: { borderLeft: '4px solid #667eea', paddingLeft: '1rem' } },
    typography: {
      baseFontSize: 'clamp(8px, 0.85vw, 11.5px)',
      fontFamily: '"Poppins", "Helvetica Neue", sans-serif',
      headerFontSize: '2.4rem',
      lineHeight: 1.6,
    },
  },
};

export const defaultPreset = resumePresets.classic;
